#!/bin/bash

# Author: Jonathan Sanfilippo
# Program: debclean
# Date: Feb 11 2023 - Birmingham, United Kingdom. 
# Copyright (C) 2023 Jonathan Sanfilippo <jonathansanfilippo.uk@gmail.com>
#
#Licenses:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.



#url
url="$HOME/.config/dsm/data/console.json"
chSet="$HOME/.config/dsm/data/checkSet.json"


#var
CHECK=$( expr "$(cat $chSet)" \* 60) 

get_updates(){
    num=$(apt list --upgradable) 
    updates=$(apt list --upgradable | grep -c upgradable)
    
}


get_updates 
    if [ "$updates" -eq 1 ]; then
        echo "$updates package upgradable" > "$url"
        echo "" >> "$url"
        echo "$num" >> "$url" 
        notify-send -i "$ICON" "Update available" "There are $updates update available" -u critical




    elif [ "$updates" -ge 1 ]; then
        echo "$updates packages upgradable" > "$url"
        echo "" >> "$url"
        echo "$num" >> "$url" 
        notify-send -i "$ICON" "Updates available" "There are $updates updates available" -u critical


    else

         echo "system updated" > "$url"
         echo "last check at $(date +'%F %T')" >> "$url"
    fi


